### ISSUE TITLE
Overall API proposal

### ISSUE THREAD

**Issue by smola** [src-d/spark-api#1]
Create an overall API proposal. Initially this is expected to:

- Load repositories from rooted repository storage (borges-style)
- Load repositories from URL list
- Extract files
- Detect language
- Parse files into UAST with Babelfish

**Comment by smola** [comment]
Stuff that requires more thought:

* A lot of functionality that is independent from Spark would be available from the JVM without Spark...
  * ...but do we need to access any of that from Python without PySpark?
  * Would it make sense to use [py4j](https://www.py4j.org) to call JVM code from Python when not using PySpark? (that's what uses PySpark under the hood), note that it requires an external JVM process in addition to the Python interpreter.

**Comment by smola** [comment]
Here is a PR exploring some aspects of the API: https://github.com/src-d/spark-api/pull/2

**Comment by smola** [comment]
Here is a PR exploring some aspects of the API: https://github.com/src-d/spark-api/pull/2

**Comment by marnovo** [comment]
@ajnavarro take a look.

**Comment by bzz** [comment]
WIP on design document is https://docs.google.com/document/d/10oFiLH4xt0ocG9URmrIk8YbzeoFaMc3_XNQ3jw4guHo/edit#heading=h.cwzn9hq61t2t
