### ISSUE TITLE
[DS] Model iterators

### ISSUE THREAD

**Issue by ajnavarro** [src-d/spark-api#12]
We need a way to transform `model (repository,reference,commit,blob) -> Iterator[Row]`
It should be an abstract class with all the generic code for all the models, and specific code to generate rows per each model.

This iterator should be able to process more than one repository in a lazy way.

**Comment by ajnavarro** [comment]
Assign to @ajnavarro

**Comment by ajnavarro** [comment]
- RepositoryIterator: https://github.com/src-d/spark-api/pull/20
- ReferenceIterator: https://github.com/src-d/spark-api/pull/20
- CommitIterator: Pending
- BlobIterator: Pending. Mandatory have filtering logic implemented

**Comment by bzz** [comment]
CommitIterator #21 
BlobIterator #25
