### ISSUE TITLE
[DS] Array[Filter] to list of properties to filter

### ISSUE THREAD

**Issue by ajnavarro** [src-d/spark-api#14]
Having a list of `org.apache.spark.sql.sources.Filter` we should transform all of them to two lists: include and exclude params.

Per example if we want to get `repository_id` filters we should be able to do something like: 
```scala
val filters = processFilters(filters: Array[Filter]): Map[String, (include:Seq[T], exclude:Seq[T])]
val repoFilters = filters("repository_id").getOrElse((Seq(),Seq()))
```
We only should take into account this filters:
- And
- Or
- [Not]Equals
- In

We should ignore by now:
- StringStartsWith
- StringEndsWith
- StringContains

**Comment by ajnavarro** [comment]
Assign to @mcarmonaa

**Comment by bzz** [comment]
Shall we also close this guy for now?
