### ISSUE TITLE
[API] Query UAST using xpath

### ISSUE THREAD

**Issue by bzz** [src-d/spark-api#30]
Depends on #7 and the status of making libuast available in scala client, but we want to have an API to make xpath queries to the UASTs.

**Comment by bzz** [comment]
Depends on `libuast` availability in the bblfsh/client-scala

**Comment by bzz** [comment]
bblfsh/client-scala \w libuast and xpath support [was release](https://github.com/bblfsh/client-scala/releases/tag/v1.0.0), this has been addressed in #115

**Comment by bzz** [comment]
Shall we close this?

**Comment by erizocosmico** [comment]
Yup
On Wed, 18 Oct 2017 at 18:55, Alexander <notifications@github.com<mailto:notifications@github.com>> wrote:

Shall we close this?
