### ISSUE TITLE
Prepare a Docker image \w Jupyter and Spark API

### ISSUE THREAD

**Issue by bzz** [src-d/spark-api#35]
This would allow:
 - something, that everyone can run, to get the latest state of Spark API
 - consists of a docker image \w hostPath mounted siva files
 - has 1 notebook \w example of PySpark using Spark API

**Comment by bzz** [comment]
- Make dockerfile
 - make a versioned image on tag by CI
 - include notebook, but it needs to be updated manually

**Comment by bzz** [comment]
Recent work has been tracked in SparkAPI repo under https://github.com/src-d/spark-api/pull/38

**Comment by erizocosmico** [comment]
This is done, right?

**Comment by ajnavarro** [comment]
Closed by https://github.com/src-d/spark-api/pull/38
