### ISSUE TITLE
[API] Detect language

### ISSUE THREAD

**Issue by ajnavarro** [src-d/spark-api#6]

**Comment by bzz** [comment]
@mcarmonaa if you do not mind, I would be happy to start looking into adding `.classifyLanguages()` API call to `Implicits` that uses an UDF \w enry-java.

**Comment by mcarmonaa** [comment]
@bzz let me rebase on the current master and I'll do it the PR. It's already working although you have to get enry-java in your [local machine](https://github.com/src-d/enry/tree/master/java)
