### ISSUE TITLE
Add scalastyle to project

### ISSUE THREAD

**Issue by ajnavarro** [src-d/spark-api#60]
http://www.scalastyle.org/

We should choose witch configuration file is for us. I previously used the twitter one: http://twitter.github.io/effectivescala/#Formatting

**Comment by erizocosmico** [comment]
That one looks fine to me
On Thu, 28 Sep 2017 at 10:21, Antonio Navarro Perez <notifications@github.com<mailto:notifications@github.com>> wrote:

http://www.scalastyle.org/

We should choose witch configuration file is for us. I previously used the twitter one: http://twitter.github.io/effectivescala/#Formatting
